# Generated by Django 5.2.3 on 2025-07-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingOptionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('trade_datetime', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('trade_price', models.FloatField()),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('proceeds', models.FloatField(blank=True, null=True)),
                ('comm_fee', models.FloatField(blank=True, null=True)),
                ('basis', models.FloatField(blank=True, null=True)),
                ('realized_pl', models.FloatField(blank=True, null=True)),
                ('mtm_pl', models.FloatField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('underlying', models.CharField(max_length=20)),
                ('strike_price', models.FloatField()),
                ('expiration_date', models.DateField()),
                ('option_type', models.CharField(choices=[('call', 'Call'), ('put', 'Put')], max_length=4)),
                ('moneyness', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'testing_options_data',
                'ordering': ['-trade_datetime'],
            },
        ),
    ]
