# Generated by Django 5.2.3 on 2025-07-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_modeltrainingresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltrainingresult',
            name='training_inputs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
